[pytest]
# addopts позволяет выставить параметры, которые автоматически добавляет прописанные параметры и флаги при обычном запуске Pytest
addopts = -s -v

# strict_markers = true Параметр, который выкидывает ошибку, если в тестах есть незарегестрированный маркер
python_files = test_*.py *_test.py
python_classes = Test*
python_functions = test_*
markers =
    slow: description
    fast: for fast tests
    regression: for regress
    smoke: for smoke
    users: for test test_create_user in test_users.py
    authentication: for authentication tests
    files: for test files
    courses: for test courses

# команда pytest --markers выводит в консоль описание по существующим маркерам

