[pytest]
# strict_markers = true Параметр, который выкидывает ошибку, если в тестах есть незарегестрированный маркер
python_files = test_*.py *_test.py
python_classes = Test*
python_functions = test_*
markers =
    slow: description
    fast: for fast tests
    regression: for regress
    smoke: for smoke
    users
# команда pytest --markers выводит в консоль описание по существующим маркерам